swagger: "2.0"
info: 
  title: DeHoli Apis Documentations v1
  description: Apis Documentations for DeHoli SuperApps
  version: 1.0.0
  contact: 
    email: donihadimas.dev@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
termsOfService: http://swagger.io/terms/    
schemes: [http. https]

paths:
# ? Categories
  /api/v1/categories:
    get:
      tags:
        - CATEGORIES
      description: Endpoint for Get All Categories
      summary: Get All Category
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: The page number for pagination (default: 1)
          required: false
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: The number of items per page (default: 10)
          required: false
          type: integer
          default: 10  
        - name: search
          in: query
          description: Search by category name
          required: false
          type: string
      responses:
        '200':
          description: Success get List Of Categories.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                categoryName:
                  type: string
                totalProductInCategory:
                  type: integer
    post:
      tags:
        - CATEGORIES
      summary: Create Categories
      description: Endpoint to Create Category
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: categories
          schema:
            type: object
            properties:
              categoryName: 
                type: string    
              totalProductInCategory: 
                type: integer    
      responses:
        '201':
          description: Create Categories.
  /api/v1/categories/{id}:
    get:
      tags:
        - CATEGORIES
      summary: Get Category by id
      description: Endpoint for Get Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory:
                type: integer
    put:
      tags:
        - CATEGORIES
      summary: Update Category by id
      description: Endpoint for Update Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: body
          name: categories
          schema:
            type: object
            properties:
              categoryName: 
                type: string       
              totalProductInCategory: 
                type: integer       
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory: 
                type: integer                             
    delete:
      tags:
        - CATEGORIES
      summary: Delete Category by id
      description: Endpoint for Delete Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory: 
                type: integer     
                           