swagger: "2.0"
info: 
  title: DeHoli Apis Documentations v1
  description: Apis Documentations for DeHoli SuperApps
  version: 1.0.0
  contact: 
    email: donihadimas.dev@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
termsOfService: http://swagger.io/terms/    
schemes: ["http", "https"]

paths:
# ? Categories
  /api/v1/categories:
    get:
      tags:
        - CATEGORIES
      description: Endpoint for Get All Categories
      summary: Get All Category
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: The page number for pagination (default: 1)
          required: false
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: The number of items per page (default: 10)
          required: false
          type: integer
          default: 10  
        - name: search
          in: query
          description: Search by category name
          required: false
          type: string
      responses:
        '200':
          description: Success get List Of Categories.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                categoryName:
                  type: string
                totalProductInCategory:
                  type: integer
    post:
      tags:
        - CATEGORIES
      summary: Create Categories
      description: Endpoint to Create Category
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: categories
          schema:
            type: object
            properties:
              categoryName: 
                type: string    
              totalProductInCategory: 
                type: integer    
      responses:
        '201':
          description: Create Categories.
  /api/v1/categories/{id}:
    get:
      tags:
        - CATEGORIES
      summary: Get Category by id
      description: Endpoint for Get Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory:
                type: integer
    put:
      tags:
        - CATEGORIES
      summary: Update Category by id
      description: Endpoint for Update Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: body
          name: categories
          schema:
            type: object
            properties:
              categoryName: 
                type: string       
              totalProductInCategory: 
                type: integer       
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory: 
                type: integer                             
    delete:
      tags:
        - CATEGORIES
      summary: Delete Category by id
      description: Endpoint for Delete Category by id Category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              categoryName:
                type: string
              totalProductInCategory: 
                type: integer     
# ? Categories
# ? Employees
  /api/v1/employees:
    get:
      tags:
        - EMPLOYEES
      description: Endpoint for Get All Employees
      summary: Get All Employees
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: The page number for pagination (default: 1)
          required: false
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: The number of items per page (default: 10)
          required: false
          type: integer
          default: 10  
        - name: search
          in: query
          description: Search by employees name
          required: false
          type: string
      responses:
        '200':
          description: Success get List Of Employees.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                employeeUsername:
                  type: string
                employeeFullName:
                  type: string
                employeePhoneNumber:
                  type: string
                employeeAddress:
                  type: string
                employeeRole:
                  type: string
    post:
      tags:
        - EMPLOYEES
      summary: Create Employees
      description: Endpoint to Create Employees
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: employees
          schema:
            type: object
            properties:
              employeeUsername: 
                type: string
              employeeFullName: 
                type: string
              employeePhoneNumber: 
                type: string
              employeeAddress: 
                type: string
              employeeRole: 
                type: string
      responses:
        '201':
          description: Create Employees.
  /api/v1/employees/{id}:
    get:
      tags:
        - EMPLOYEES
      summary: Get Employees by id
      description: Endpoint for Get Employees by id Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              employeeUsername:
                type: string
              employeeFullName:
                type: string
              employeePhoneNumber:
                type: string
              employeeAddress:
                type: string
              employeeRole:
                type: string
    put:
      tags:
        - EMPLOYEES
      summary: Update Employees by id
      description: Endpoint for Update Employees by id Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: body
          name: employees
          schema:
            type: object
            properties:
              employeeUsername: 
                type: string
              employeeFullName: 
                type: string
              employeePhoneNumber: 
                type: string
              employeeAddress: 
                type: string
              employeeRole: 
                type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              employeeUsername:
                type: string                         
              employeeFullName:
                type: string                         
              employeePhoneNumber:
                type: string                         
              employeeAddress:
                type: string                         
              employeeRole:
                type: string                         
    delete:
      tags:
        - EMPLOYEES
      summary: Delete Employees by id
      description: Endpoint for Delete Employees by id Employees
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              employeeUsername:
                type: string     
              employeeFullName:
                type: string     
              employeePhoneNumber:
                type: string     
              employeeAddress:
                type: string     
              employeeRole:
                type: string     
# ? Employees                             
# ? Roles
  /api/v1/roles:
    get:
      tags:
        - ROLES
      description: Endpoint for Get All Roles
      summary: Get All Roles
      produces:
        - application/json
      parameters:
        - name: page
          in: query
          description: The page number for pagination (default: 1)
          required: false
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: The number of items per page (default: 10)
          required: false
          type: integer
          default: 10  
        - name: search
          in: query
          description: Search by roles name
          required: false
          type: string
      responses:
        '200':
          description: Success get List Of Roles.
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                rolesName:
                  type: string
                permissions:
                  type: string
    post:
      tags:
        - ROLES
      summary: Create Roles
      description: Endpoint to Create Roles
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: roles
          schema:
            type: object
            properties:
              rolesName: 
                type: string
              permissions: 
                type: string
      responses:
        '201':
          description: Create Roles.
  /api/v1/roles/{id}:
    get:
      tags:
        - ROLES
      summary: Get Roles by id
      description: Endpoint for Get Roles by id Roles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              rolesName:
                type: string
              permissions:
                type: string
    put:
      tags:
        - ROLES
      summary: Update Roles by id
      description: Endpoint for Update Roles by id Roles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - in: body
          name: roles
          schema:
            type: object
            properties:
              rolesName: 
                type: string
              permissions: 
                type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              rolesName:
                type: string                         
              permissions:
                type: string                      
    delete:
      tags:
        - ROLES
      summary: Delete Roles by id
      description: Endpoint for Delete Roles by id Roles
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              id:
                type: string
              rolesName:
                type: string     
              permissions:
                type: string
# ? Roles         